jdbc:
  url: jdbc:mysql://localhost:3306/cateringdb?useSSL=false
  username: root
  password: 1234
  poolSize: 10
  driverClassName: com.mysql.jdbc.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

#  spring.autoconfigure.exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
